# Site wide configuration

title: Higher Order Functions
locale: en_US
url:
timezone: America/Chicago
encoding: utf-8


# Jekyll configuration
permalink:  /:categories/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Tristan Mahr
  avatar: bio-photo.jpg
  bio: "Language and data scientist"
  email:
  disqus-shortname:
  twitter: tjmahr
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: tjmahr
  stackoverflow: 1084259/tj-mahr
  #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "tjmahr.github.io.Rproj", ".Rproj.user"]


# Atom

atom:
  buildCommand:
    - C:\Ruby22-x64\bin\bundle
    - exec
    - jekyll
    - build
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _posts
    - _drafts
  defaultPostDir:
    - _posts
